apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fasterwhisper-models
  namespace: fasterwhisper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
